### ISSUE TITLE
Intentional Removal from NPM?

### ISSUE THREAD

**Issue by jangerhofer** [floatdrop/timed-out#13]
I noticed that this package has been [removed from the NPM registry](https://www.npmjs.com/package/timed-out) while installing a project which depends on `timed-out`.  As far as I can tell, the removal was recent -- [from the last two days or so.](https://webcache.googleusercontent.com/search?q=cache:meemXeC_cJUJ:https://www.npmjs.com/package/timed-out+&cd=1)

Please disregard my issue ticket if the change was intentional; I merely want to make sure you, @floatdrop, are aware!

**Comment by antoniobrandao** [comment]
Same problem here. Trying to install 

    nodemon-webpack-plugin

fails because timed-out is missing.

But NPM modules are supposedly impossible to remove by users at this point so this might be a problem with NPM. Also other NPM modules are not showing up, and later showing up again.

Probably a NPM registry problem.

**Comment by antoniobrandao** [comment]
They say the status is OK

https://status.npmjs.org/

**Comment by jangerhofer** [comment]
> NPM modules are supposedly impossible to remove by users at this point 

I did not know that, but that policy certainly makes sense!  Perhaps it is simply a temporary outage.

**Comment by antoniobrandao** [comment]
https://docs.npmjs.com/cli/unpublish

Quote:
"With the default registry (registry.npmjs.org), unpublish is only allowed with versions published in the last 24 hours. If you are trying to unpublish a version published longer ago than that, contact support@npmjs.com."

I've been having this problem installing other webpack-related modules, and some of them have been restored in the meanwhile. Eagerly awaiting for timed-out to come back too.

**Comment by teawithfruit** [comment]
It's not only the timed-out package. https://www.npmjs.com/package/pinkie is another package of @floatdrop and it's gone too. I hope that this is a temporarily npm registry error.

**Comment by JAertgeerts** [comment]
I have the same with require-from-string, most likely npm

**Comment by antoniobrandao** [comment]
https://github.com/npm/registry/issues/255

**Comment by girishla** [comment]
yep, same problem

**Comment by jangerhofer** [comment]
I had the same error from ‘require-from-string’ about half an hour ago, but it resolved itself before I posted this issue. Seems like it should work itself out indeed.

**Comment by antoniobrandao** [comment]
@jangerhofer yeah some packages seem to come back, some others not.

Just today I've seen the package "infinity-agent" come back, disappear again, and come back again.

Very flimsy behaviour from NPM.

**Comment by teawithfruit** [comment]
https://twitter.com/npmstatus/status/949728719450460161

**Comment by jasonbarry** [comment]
All of @floatdrop's packages are missing... https://www.npmjs.com/~floatdrop

**Comment by tommymcdonald** [comment]
Creating a new `create-react-native-app` package fails on this as well, this is a very large project dependency.

**Comment by mhingston** [comment]
Related: [Many packages suddenly disappeared #255](https://github.com/npm/registry/issues/255)

**Comment by antoniobrandao** [comment]
Beware before visiting https://github.com/npm/registry/issues/255

You can't unsee.
