### ISSUE TITLE
OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by Valkyrihane** [floatdrop/timed-out#28]
Hi! 👋 
Firstly, thanks for your work on this project! 🙂
Today I used [patch-package](https://github.com/ds300/patch-package) to patch `timed-out@4.0.1` for the project I'm working on.

`._headers` access function has been deprecated since Node **v12**. **v14** being the current LTS, while **v16** is active, it would be nice to upgrade the used method in order to avoid deprecation warnings/errors on builds (in my case building my gatsby website)

A related issue (#25) was opened then closed by its author without any real solution  (I'm not using `npm-name`)

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/timed-out/index.js b/node_modules/timed-out/index.js
index 94007a4..fc40d52 100644
--- a/node_modules/timed-out/index.js
+++ b/node_modules/timed-out/index.js
@@ -6,7 +6,7 @@ module.exports = function (req, time) {
 	}
 
 	var delays = isNaN(time) ? time : {socket: time, connect: time};
-	var host = req._headers ? (' to ' + req._headers.host) : '';
+	var host = req.getHeaders() ? (' to ' + req.getHeaders().host) : '';
 
 	if (delays.connect !== undefined) {
 		req.timeoutTimer = setTimeout(function timeoutHandler() {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by sindresorhus** [comment]
This has already been fixed some versions ago. Please do a bit of effort before opening an issue.

**Comment by Valkyrihane** [comment]
This one's on me, an old version of timed-out was used in my dependency tree, and I checked the wrong commit on github. Sorry for the unneeded issue !
